#!/bin/sh
echo "====== Descargando e instalando Conky ====="
sudo apt-get install conky conky-all
wget -O ConkyInfinityElementary.zip https://dl.dropbox.com/u/42476216/ConkyInfinityElementary.zip
unzip ConkyInfinityElementary.zip
rm ConkyInfinityElementary.zip
chmod +x .start-conky.sh


